from __future__ import annotations

from typing import Any

from . import ALLOWED_SEED


def render_session(current: dict[str, Any]) -> str:
    identity = current.get("identity") or {}
    resources = current.get("resources") or {}
    blind = current.get("blind") or {}
    build = current.get("build") or {}
    def shown(value: Any) -> str:
        return "unknown until save resumes" if value is None else str(value)

    lines = [
        "# Session State",
        "",
        "> Generated by `python balatroctl.py checkpoint`. Do not edit manually.",
        "",
        f"- Updated: `{current.get('updated_at')}`",
        f"- Run ID: `{identity.get('run_id')}`",
        f"- Seed: `{identity.get('seed')}`",
        f"- Bridge session: `{identity.get('bridge_session')}`",
        f"- Observation: `{identity.get('observation_id')}`",
        f"- State: `{current.get('status')}`",
        f"- Ante / round: `{shown(current.get('ante'))}` / `{shown(current.get('round'))}`",
        f"- Blind: `{shown(blind.get('name') or current.get('blind_on_deck'))}` target `{shown(blind.get('chips_required'))}`",
        f"- Chips / hands / discards / dollars: `{shown(resources.get('chips'))}` / `{shown(resources.get('hands_left'))}` / `{shown(resources.get('discards_left'))}` / `{shown(resources.get('dollars'))}`",
        f"- Jokers: `{', '.join(str(item) for item in build.get('jokers') or []) or 'none observed'}`",
        "",
        "## Next Decision",
        "",
        str(current.get("next_decision")),
        "",
    ]
    return "\n".join(lines)


def render_strategy(strategy: dict[str, Any], current: dict[str, Any] | None = None) -> str:
    current = current or {}
    supported = [rule for rule in strategy.get("rules") or [] if rule.get("status") != "rejected"]
    rejected = [rule for rule in strategy.get("rules") or [] if rule.get("status") == "rejected"]
    unresolved = [rule for rule in strategy.get("rules") or [] if rule.get("status") in {"candidate", "observed"}]
    lines = [
        f"# Balatro Strategy — Seed {ALLOWED_SEED}",
        "",
        "> Migrated to policies.db. Record evidence through `balatroctl.py strategy-record`; do not edit manually.",
        "",
        "## Objective and Invariants",
        "",
        f"- {strategy.get('objective')}",
        f"- Only allowed seed: `{ALLOWED_SEED}`.",
        "- Live observation outranks all stored state. No direct IPC writes or fixed sleeps.",
        "- Continue same run after Ante 8; never replace a resumable save.",
        "",
        "## Active Build Plan",
        "",
    ]
    lines.extend(f"- {item}" for item in strategy.get("active_build_plan") or ["No active plan recorded."])
    lines.extend(["", "## Current Ante Playbook", ""])
    ante_key = str(current.get("ante") or "unknown")
    playbook = (strategy.get("ante_playbook") or {}).get(ante_key) or []
    lines.extend(f"- {item}" for item in playbook or ["No evidence-backed ante-specific playbook yet. Use live policy state."])
    lines.extend(["", "## Evidence-Backed Rules", ""])
    lines.extend(f"- `{rule['id']}` [{rule['status']}]: {rule['directive']}" for rule in supported)
    lines.extend(["", "## Rejected Strategies", ""])
    lines.extend(
        [f"- `{rule['id']}`: {rule['directive']}" for rule in rejected]
        or ["- None. Legacy claims remain quarantined, not accepted or rejected in v2."]
    )
    lines.extend(["", "## Unresolved Hypotheses", ""])
    lines.extend(
        [f"- `{rule['id']}` [{rule['status']}]: {rule['directive']}" for rule in unresolved]
        or ["- None recorded. Add only with explicit conditions and evidence."]
    )
    lines.extend(["", "## Compact Run History", ""])
    history = strategy.get("run_history") or []
    lines.extend(
        [f"- `{item.get('run_id')}`: max ante `{item.get('max_ante')}`, result `{item.get('result')}`" for item in history[-10:]]
        or ["- No trusted v2 completed runs recorded."]
    )
    lines.append("")
    return "\n".join(lines)
